[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.. --minify -b https://ahnawab.com/"

[build.environment]
  HUGO_VERSION = "0.123.8"
  GO_VERSION = "1.22.1"
  NODE_VERSION = "20"
  HUGO_THEME = "repo"

[context.deploy-preview]
  command = "cd exampleSite && hugo --gc --themesDir ../.. --minify -b $DEPLOY_PRIME_URL"